language: generic

services:
  - docker
  
before_install:
  - sudo echo "deb [arch=amd64] http://repo.yandex.ru/yandex-browser/deb beta main" | sudo tee -a /etc/apt/sources.list
  - curl https://repo.yandex.ru/yandex-browser/YANDEX-BROWSER-KEY.GPG | sudo apt-key add -
  - sudo apt-get update -qq
  - YANDEX_APT=$(sudo apt search yandex-browser-beta | grep yandex-browser-beta)
  - REGEX="(([0-9]+\.){2}[0-9]+)\.[0-9]+-[0-9]"
  - if [[ $YANDEX_APT =~ $REGEX ]]; then :; fi
  - YANDEX_FULL_VERSION=${BASH_REMATCH}
  - YANDEX_VERSION=${BASH_REMATCH[1]}
  - echo "Yandex version ${YANDEX_FULL_VERSION}"
  - OPERADRIVER_RELEASE=$(curl --silent "https://github.com/operasoftware/operachromiumdriver/releases/latest")
  - REGEX="v\.([0-9]+\.[0-9]+)"
  - if [[ $OPERADRIVER_RELEASE =~ $REGEX ]]; then :; fi
  - OPERADRIVER_VERSION=${BASH_REMATCH[1]}
  - echo "Operadriver version ${OPERADRIVER_VERSION}"

install: true
  
script:
  - cd selenium
  - ./automate_yandex.sh $YANDEX_FULL_VERSION $OPERADRIVER_VERSION $YANDEX_VERSION
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - docker push ${DOCKER_USERNAME}/yandex:latest
  - docker push ${DOCKER_USERNAME}/yandex:${YANDEX_VERSION}
  - docker push ${DOCKER_USERNAME}/vnc_yandex:latest
  - docker push ${DOCKER_USERNAME}/vnc_yandex:${YANDEX_VERSION}